### ISSUE TITLE
Convert to a unit in the same dimension

### ISSUE THREAD

**Issue by aethr** [jscheiny/safe-units#200]
Hi, I'm wondering whether it's currently possible to convert a Measure in one unit to a Measure in another unit of the same dimension, ie from grams to kilograms.

I'm interested in something similar to #163, but returning an actual Measure object with a `.value` and `.symbol`. Using `.over()` converts the `value` properly, but it removes the dimension in the process.

The reason I would find this useful in my app is that values and units are displayed in separate span elements like:
```html
<span class="value">123</span>
<span class="unit">kg</span>
```

This makes the formatting features less useful for me. But since the `Measure` object already has a `value` and `symbol`, it seems perfect for making a display component with a single Measure prop that can print out the value and the unit.

What I'm doing now is something like:
```vue
<span class="value">{{ myMeasure.valueIn(kilograms) }}</span>
<span class="unit">{{ kilograms.symbol }}</span>
```

**Comment by jscheiny** [comment]
The purpose of a symbol on a measure is to indicate that that unit represents 1 of that symbol. For example `Measure.of(1000, meters, "km")` returns a measure that represents 1 kilometer. Under the hood, everything is represented in base dimensions so we can't actually store a measure as `{ value: 1, symbol: "km" }` because this would break any arithmetic involving that measure. Maybe we could add a method like `Measure.valueInObject(kilograms)` which returns a plain javascript object like the one above or maybe a tuple like `[1, "km"]` but this feels like a pretty clunky API and honestly not much better than what you've written above. I think what you have feels pretty idiomatic and good to me.

**Comment by aethr** [comment]
Fair enough, thanks for taking the time to explain. ❤️ 

If I wanted a "value that travels with a unit/symbol" I can always compose a higher level object:

```js
function createUnitMeasure(measure: Measure, unit: Unit) {
  return {
    measure,
    unit,
  };
}
```
